#!/bin/bash

function prefix_completion {
    [[ $# -ge 3 ]] || return 1
    local function_name="$2"
    local arg_count=$(($#-3))
    local comp_function_name="$1"
    shift 2
    local function="
function $function_name {
    ((COMP_CWORD+=$arg_count))
    COMP_WORDS=( "$@"\${COMP_WORDS[@]:1} )
    "$comp_function_name"
    return 0
}"
    # eval "$function"
    echo  $function_name
    echo "$function"
}

function alias_completion {
    [[ $# -ge 3 ]] || return 1
    local function_name="$2"
    local arg_count=$(($#-3))
    local comp_function_name="$1"
    shift 2
    local function="
function $function_name {
    ((COMP_CWORD+=$arg_count))
    COMP_WORDS=( "$@" \${COMP_WORDS[@]:1} )
    "$comp_function_name"
    return 0
}"
    # eval "$function"
    echo  $function_name
    echo "$function"
}

