#!/bin/bash

default_dir="."

if [[ $# -eq 1 ]]; then
    dir="$default_dir"
    arg="$1"
else
    dir="$1"
    arg="$2"
fi

ntdef='newtype.*=.*'
tdef='type.*=.*'
ddef='data.*=.*'

last=""

echo -e "\n\033[0;35mFunctions:"
grep -R --include='*.hs' -e :: "$dir" \
  | grep "$arg" \
  | grep -v "\-\-" \
  | while read -r line; do
    last="$file"
    file=`echo "$line" | cut -d: -f1`
    name=`echo "$line" | cut -d: -f2 | sed 's/ *::.*//'`
    def=`echo  "$line" | cut -d: -f4-`
    real=`echo "$def"  | grep "$arg"`
    if [[ -n "$real" ]]; then
        if [[ "$last" == "$file" ]]; then
            printf "\033[0;32m%-15s\033[0m::" "$name"
            echo "$def" | grep --color=auto "$arg"
        else
            echo
            echo -e "\033[0;36m$file:"
            printf "\033[0;32m%-15s\033[0m::" "$name"
            echo "$def" | grep --color=auto "$arg"
        fi
        # printf "%-30s\033[0;32m%-20s\033[0m::" "$file" "$name"
    fi
    # print with padding and recolor output
done


