#!/bin/bash

file="$1"

if [[ "$file" =~ /src/ ]]; then
    mod=`echo "$file" | sed 's,^.*src/,,' | sed 's,\.hs$,,'| tr '/' '.'`
else
    mod=`echo "$file" | sed 's,^.*/,,' | sed 's,\..*$,,'`
    res=`echo "$mod" | head -c1 - | grep '[[:upper:]]'`
    if [[ "$res" == "" ]]; then
        # lower
        mod="Main"
    # else
    #     # UPPER
    fi
fi
echo "$mod"

